version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
