version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    groups:
      non-critical-dependencies:
        exclude-patterns:
          - "spring-boot-*"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
